import React from 'react';
//import { Upload } from 'react-feather';
import { Col, Container, Row } from 'reactstrap';

import './buttons.scss'
import Buttons from './buttons/buttons';

function button() {
  return (
    <div>
      <Container>
        <Row>
          <Col>
              <div className="buttons common-space">
                  <h2 className="common-header">Button</h2>
                  <Row>
                    <Col>
                        <div className="button-lists">
                            <h6 className="label-dark mb-0">Buttons</h6>
                            <ul className="defult-btn">
                              <li></li>
                              <li><h3>Primary</h3></li>
                              <li><h3>Secondary</h3></li>
                            </ul>
                            <ul>
                              <li><span>Default</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary"
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="Secondary"
                                  colorval="primary" 
                                  icon=""
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Hover</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="hover"
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="hover"
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Disabled</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary"
                                  colorval="primary"
                                  disabledval={true}
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary"
                                  disabledval={true}
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Focus</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary"
                                  class="focus"
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="focus"
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Active</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="active"
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="active"
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                        </div>
                        <div className="button-lists btn-full">
                            <h6 className="label-dark mb-0">Long Buttons</h6>
                            <ul>
                              <li><span>Default</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="btn-block"
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="btn-block"
                                  colorval="primary" 
                                  icon=""
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Hover</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="hover btn-block"
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="hover btn-block"
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Disabled</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary"
                                  class="btn-block"
                                  disabledval={true}
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary"
                                  class="btn-block"
                                  disabledval={true}
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Focus</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="focus btn-block"
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="focus btn-block"
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Active</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="active btn-block"
                                  colorval="primary"
                                  icon="" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="active btn-block"
                                  colorval="primary"
                                  icon="" 
                                />
                              </li>
                            </ul>
                        </div>
                        <div className="button-lists">
                            <h6 className="label-dark mb-0">Buttons with icon</h6>
                            <ul>
                              <li><span>Default</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Hover</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="hover"
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="hover"
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Disabled</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary"
                                  colorval="primary"
                                  disabledval={true}
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary"
                                  colorval="primary"
                                  disabledval={true}
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Focus</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="focus"
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="focus"
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Active</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="active"
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="active"
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                        </div>
                        <div className="button-lists btn-full">
                            <h6 className="label-dark mb-0">Long Buttons with icon</h6>
                            <ul>
                              <li><span>Default</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Hover</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="hover btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="hover btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Disabled</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary"
                                  class="btn-block"
                                  colorval="primary"
                                  disabledval={true}
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary"
                                  class="btn-block"
                                  colorval="primary"
                                  disabledval={true}
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Focus</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="focus btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="focus btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                            <ul>
                              <li><span>Active</span></li>
                              <li>
                                <Buttons 
                                  outlineval=""
                                  name="primary" 
                                  class="active btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />  
                              </li>
                              <li>
                                <Buttons 
                                  outlineval="true"
                                  name="secondary" 
                                  class="active btn-block"
                                  colorval="primary"
                                  icon="true" 
                                />
                              </li>
                            </ul>
                        </div>
                    </Col>
                  </Row>
              </div>
          </Col>
        </Row>
      </Container>
          
    </div>
  );
}

export default button;
